# Generated by Django 4.2.7 on 2023-11-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='login_time',
        ),
    ]
