# Generated by Django 4.2.7 on 2023-11-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_remove_employee_login_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='login_time',
            field=models.TimeField(default=True),
        ),
    ]
