# Generated by Django 4.2.7 on 2023-11-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_employee_login_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='login_time',
        ),
    ]
